/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import oblssoo.Sistema;

/**
 *
 * @author Graziano
 */
public class mainMenu extends javax.swing.JFrame {

    private static Sistema sistema;

    public mainMenu(Sistema s) {
        initComponents();
        sistema = s;
        txtSesion.setText("En Sesion: " + sistema.getEnSesion().toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonVerProgramasCargados = new javax.swing.JButton();
        buttonEjecutarProcesos = new javax.swing.JButton();
        buttonVerPermisos = new javax.swing.JButton();
        buttonCargarPrograma = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();
        buttonCerrarSesion = new javax.swing.JButton();
        buttonVerRecursos = new javax.swing.JButton();
        txtSesion = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonVerProgramasCargados.setText("Ver Programas Cargados");
        buttonVerProgramasCargados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerProgramasCargadosActionPerformed(evt);
            }
        });

        buttonEjecutarProcesos.setText("Ejecutar Procesos");
        buttonEjecutarProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEjecutarProcesosActionPerformed(evt);
            }
        });

        buttonVerPermisos.setText("Ver Permisos");
        buttonVerPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerPermisosActionPerformed(evt);
            }
        });

        buttonCargarPrograma.setText("Cargar Programa");
        buttonCargarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCargarProgramaActionPerformed(evt);
            }
        });

        buttonSalir.setText("SALIR");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        buttonCerrarSesion.setText("Cerrar Sesion");
        buttonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarSesionActionPerformed(evt);
            }
        });

        buttonVerRecursos.setText("Ver Recursos");
        buttonVerRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerRecursosActionPerformed(evt);
            }
        });

        txtSesion.setText("En Sesion: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(buttonCargarPrograma))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonCerrarSesion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonVerRecursos)
                            .addComponent(buttonVerPermisos))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 116, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonVerProgramasCargados)
                                .addGap(119, 119, 119))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonEjecutarProcesos)
                                .addGap(138, 138, 138))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(buttonEjecutarProcesos)
                .addGap(18, 18, 18)
                .addComponent(buttonVerProgramasCargados)
                .addGap(18, 18, 18)
                .addComponent(buttonVerPermisos)
                .addGap(21, 21, 21)
                .addComponent(buttonVerRecursos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCargarPrograma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(buttonCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalir)
                    .addComponent(txtSesion))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVerProgramasCargadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerProgramasCargadosActionPerformed
        // TODO add your handling code here:
        verProgramas v = new verProgramas(sistema);
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonVerProgramasCargadosActionPerformed

    private void buttonEjecutarProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEjecutarProcesosActionPerformed
        verPermisos v = new verPermisos(sistema);
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonEjecutarProcesosActionPerformed

    private void buttonVerPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerPermisosActionPerformed
        verPermisos v = new verPermisos(sistema);
        v.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVerPermisosActionPerformed

    private void buttonCargarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCargarProgramaActionPerformed
        cargarPrograma v = new cargarPrograma(sistema);
        v.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCargarProgramaActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void buttonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesionActionPerformed
        logIn ventLogin = new logIn(sistema);
        ventLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCerrarSesionActionPerformed

    private void buttonVerRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerRecursosActionPerformed
        verRecursos v = new verRecursos(sistema);
        v.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVerRecursosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCargarPrograma;
    private javax.swing.JButton buttonCerrarSesion;
    private javax.swing.JButton buttonEjecutarProcesos;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JButton buttonVerPermisos;
    private javax.swing.JButton buttonVerProgramasCargados;
    private javax.swing.JButton buttonVerRecursos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtSesion;
    // End of variables declaration//GEN-END:variables
}
